### PR TITLE
Conform UUID to BSONValue

### PR DESCRIPTION
**Pull request by valeriomazzeo**
Fixes https://github.com/mongodb/mongo-swift-driver/issues/161

### CODE REVIEW

**Comment by kmahar** [comment]
Hi @valeriomazzeo, thanks so much for the PR. Would you be willing to add a test showcasing how this works in `BSONValueTests.swift`?

**Comment by valeriomazzeo** [comment]
Sure, will do as soon as I can, probably on Monday.

This is how `UUID` are saved right now:
screenshot 2018-12-07 at 17 16 04

This is how they are saved with this PR:
screenshot 2018-12-07 at 17 15 19

**Comment by valeriomazzeo** [comment]
@kmahar I have added a test which is highlighting a major issue.
I was expecting  that by conforming a type to `BSONValue`, `BSONEncoder`/`BSONDecoder` would automatically `encode`/`decode` such type.

What's happening is that just as a coincidence the encoding works, because everything is transformed to a `Document` before being written to the database, de facto triggering a call to `func encode(to storage: DocumentStorage, forKey key: String)`.

Unfortunately, that doesn't happen during decoding for `static func from(iterator iter: DocumentIterator) throws -> BSONValue`.

In fact there's no trace of any call to `BSONValue` encoding/decoding methods from inside `BSONEncoder`/`BSONDecoder`.

I spent some time going through `BSONEncoder`/`BSONDecoder` source code, but at this time I am not sure what was the intended behaviour.

What am I missing?

**Comment by mbroadst** [comment]
Hi @valeriomazzeo, I took a quick look at your problem this afternoon.

The reason you are running into trouble here is that `UUID` provides its own Codable [initializer](https://github.com/apple/swift/blob/master/stdlib/public/Darwin/Foundation/UUID.swift#L165-L175) which expects the data to be a `String`. Since `UUID` is defined as a struct you can't override this method, so we'd probably have to investigate adding something like a `uuidDecodingStrategy` similar to `JSONDecoder`s [dateDecodingStrategy](https://developer.apple.com/documentation/foundation/jsondecoder/2895216-datedecodingstrategy). 

Thoughts @kmahar, @jmikola?

**Comment by valeriomazzeo** [comment]
@mbroadst I totally agree. It seems like the proper way to go. 👍

**Comment by valeriomazzeo** [comment]
Closing this as it's been made obsolete by #176

**Pull request closed without merging**
