### PR TITLE
SWIFT-1616 ⁃ Impossible to create a text index with default name

### PR DESCRIPTION
**Pull request by valeriomazzeo**
Fixes https://github.com/mongodb/mongo-swift-driver/issues/768

### CODE REVIEW

**Review by patrickfreed — CHANGES_REQUESTED** [review]
Thanks for identifying this issue and submitting this PR!

The logic looks good, but could we add a test verifying that it fixes the original issue? You can just put it in `AsyncAwaitTests.swift` and use the async/await syntax.

**Comment by valeriomazzeo** [comment]
@patrickfreed done.

**Review by kmahar — APPROVED** [review]

**Review by patrickfreed — APPROVED** [review]
LGTM, thanks for the contribution!

**Comment by valeriomazzeo** [comment]
👍🏻

**Pull request merged**
